#!/usr/bin/env python3

import rospy
from pointcloud2simmodel.cloudcollector import PointCloud2Collector

if __name__ == "__main__":
    rospy.init_node("pointcloud2_to_sdf")
    rospy.loginfo("Starting pointcloud2_to_sdf node")
    PointCloud2Collector("/camera/depth/color/points") # TODO: allow setting topic name via rosparam
    rospy.loginfo("Ready to receive pointclouds")
    rospy.spin()
